### ISSUE TITLE
Can Find Package -- Import failing

### ISSUE THREAD

**Issue by rduart** [jdub1581/MapGenerator#1]
For some reason the package org.jtp.heightmapgenerator.utils.Vertex; is missing from the down load Could you please update the source to include it.

Thanks,

Randy

**Comment by jdub1581** [comment]
This was an old experiment I was doing.. Why Vertex is there? I am not sure...
Vertex was simply a  javafx.scene.shape.Box .. Used for visualizing the geometry when creating other shapes. I thought I removed all references to it.. 

My main project is FXYZ, and I will eventually clean this up so just be patient..

**Comment by rduart** [comment]
No worries.  I was looking for an alternative to using JOGL with JavaFX.  I came across you project in my search.   I will take a look at FXYZ project.    

Thank you for the quick reply.

Randy

**Comment by jdub1581** [comment]
Yes check it out... we are constantly adding new things... 
this is the active repo : https://github.com/Birdasaur/FXyz 
I have another but that is for once we do an official release.
There is also a FXYZ development repo for random experiments,
and FYzx (eventually will be a port of jbullet physics built for Javafx)

The last 2 you can find through my page..

**Comment by rduart** [comment]
Just took a look.  FXYZ looks like great work.  Also I fixed this sample.  It was easy to fix once you pointed out it was a javafx.scene.shape.Box.  Later this week I will dig a little deeper into your FXYZ, and FYzx.

Many thanks...
